# Site settings
title: Lokesh Pahal - Web Developer / Wordpress Developer
email: contact@lokeshpahal.com
description: > # this means to ignore newlines until "baseurl:"
  Front End Developer / Web Developer. Since 4 years I am fascinated with front-end technologies, 
  magic and possibilities of HTML5 / CSS3 / JavaScript and Wordpress And also Plays with PHP and Python
base_url: "http://lokeshpahal.com"
url: "http://lokeshpahal.com"


twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# Google Analytics
gahandler: 'UA-57759089-1'
# Disqus
disqushandler: 'lokeshpahal'

# Blog Configurations
permalink: /:categories/:title/
paginate: 10
paginate_path: '/wall/page:num/'
destination: ./_site