# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Lokesh Pahal'
tagline:          'Web Developer'
description:      'All about Lokesh Pahal'
url:              'http://lokeshpahal.com'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Lokesh Pahal'
linkedin:       'https://www.linkedin.com/pub/lokesh-kumar/36/230/752'
twitter:        'https://twitter.com/lokeshpahal'
facebook:       'https://www.facebook.com/lokesh.pahal.1'
gplus:          'https://plus.google.com/114916235383203852306/'

# Google Analytics
gahandler: 'UA-52149651-1'

# Disqus
disqushandler: 'lokeshpahal'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
